# Generated by Django 5.2.10 on 2026-03-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non Veg')], default='veg', max_length=10),
            preserve_default=False,
        ),
    ]
